### PR TITLE
Update ray_intersect_box.cpp

### PR DESCRIPTION
**Pull request by Ian729**
I think you need to comment out the whole parameter, only commenting out "t" will result in an error:
candidate function not viable: requires 5 arguments, but 4 were provided
bool ray_intersect_box(

### CODE REVIEW

**Comment by velociraptor111** [comment]
It works fine for me , you just have to supply 5 arguments .. This way it is safe for everyone.

If the prof makes this change(as you proposed) then this merge would break everyone else's code who were working before he even commented out the t in the first place.

**Comment by Ian729** [comment]
I see, but the prof says t is ignored, does that mean we don't need to use t in our function?

**Comment by velociraptor111** [comment]
Yeah, so you could supply like a dummy t variable that will not get used anywhere in the function at all ..

Initially the confusion was that I was also wondering what the variable t is for since we're only interested in finding out if the ray hits a particular box or not ..

**Comment by Ian729** [comment]
thanks

**Pull request closed without merging**
